#!/bin/bash

PATH=/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin
source ~/.bashrc

if [ -z "$2" ]
  then
  echo "Usage: $0 <data_type> <file>"
  echo "  eg $0 postgres my_table.date.gz"
  exit
fi

targetdir="/$MANTA_USER/stor/backups/$1/$(hostname)"
file=$(echo -n $2 | awk 'BEGIN{FS="/"}{ print ( $(NF-0) ) }')
log_date=$(date '+%d/%b/%Y:%H:%M:%S %z')

mmkdir -p $targetdir

if [ $(md5sum $2 | awk '{print $1}') == $(echo -n "$targetdir/$file" | mjob create -q -o md5sum 2> /dev/null | awk '{print $1}') ]; then
  echo "[$log_date] $targetdir/$file already exists and has the same checksum as $2.  Skipping..."
  exit 0
fi

echo "[$log_date] Backing up $2 to $targetdir/$file..."
mput -q -f $2 $targetdir/$file

if [ $(md5sum $2 | awk '{print $1}') != $(echo -n "$targetdir/$file" | mjob create -q -o md5sum 2> /dev/null | awk '{print $1}') ]; then
  echo "[$log_date] The checksum for $2 doesn't match the checksum for $targetdir/$file.  Backup failed.  Exiting..."
  exit 1
fi
